AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.5

LineLength:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false	  

Style/AsciiComments:
  Enabled: false

MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb' 
    - 'config/routes.rb' 

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
